### ISSUE TITLE
Accidentally checked in file?

### ISSUE THREAD

**Issue by gevhaz** [lupont/posh#3]
Should this file be checked in? 

https://github.com/lupont/rush/blob/dev/ansi-colors.sh

It's from a commit with the subject "Fix formatting errors".

**Comment by lupont** [comment]
Indeed it should not, thanks! Fixed in [c5484eb](https://github.com/lupont/rush/commit/c5484ebb1f8aa6d720bfd42f953be8e6c41a14ad)
